import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import ReactQueryProvider from '@/components/providers/react-query-provider';
import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/components/providers/auth-provider';

export const metadata: Metadata = {
  title: 'Rebound',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          // geistSans.variable,
          // geistMono.variable,
          'antialiased',
          'flex flex-col min-h-svh h-svh'
        )}
      >
        <ReactQueryProvider>
          <AuthProvider>{children}</AuthProvider>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
